### PR TITLE
[RFR] Make Make commands silent

### PR DESCRIPTION
**Pull request by fzaninotto**
Before:

```
➜  quarto-python git:(master) make run
docker run --interactive --rm -v "/code" --name quarto-python quarto-python python ./src/quarto.py
TERM environment variable not set.

Welcome to Quarto-Py
```

After:

```
➜  quarto-python git:(master) ✗ make run
TERM environment variable not set.

Welcome to Quarto-Py
```

### CODE REVIEW

**Comment by Kmaschta** [comment]
@fzaninotto 
Know the command of the makefile is useful for debug and CI, IMHO

You can put this line in your bashrc / zshrc to supress all make commands:

```
alias make='make -s'
```

**Comment by fzaninotto** [comment]
I disagree. When I run a command, I want information, not noise. If I want debug information, I ask a verbose flag.

**Comment by JulienMattiussi** [comment]
Closed by #9

**Comment by JulienMattiussi** [comment]
Done in #9

**Pull request closed without merging**
